-- -----------------------------------------------------------------------------
--       CREATION DES REFERENCES DE TABLE
-- -----------------------------------------------------------------------------


ALTER TABLE PAIEMENT ADD (
     CONSTRAINT FK_PAIEMENT_COMMANDE
          FOREIGN KEY (CMD_NUM)
               REFERENCES COMMANDE (CMD_NUM))   ;

ALTER TABLE COMMANDE ADD (
     CONSTRAINT FK_COMMANDE_CLIENT
          FOREIGN KEY (CLI_ID)
               REFERENCES CLIENT (CLI_ID))   ;

ALTER TABLE LIVRAISON ADD (
     CONSTRAINT FK_LIVRAISON_COMMANDE
          FOREIGN KEY (CMD_NUM)
               REFERENCES COMMANDE (CMD_NUM))   ;

ALTER TABLE ARTICLE ADD (
     CONSTRAINT FK_ARTICLE_EDITEUR
          FOREIGN KEY (EDIT_ID)
               REFERENCES EDITEUR (EDIT_ID))   ;

ALTER TABLE THEMATISER ADD (
     CONSTRAINT FK_THEMATISER_ARTICLE
          FOREIGN KEY (ART_NUM)
               REFERENCES ARTICLE (ART_NUM))   ;

ALTER TABLE THEMATISER ADD (
     CONSTRAINT FK_THEMATISER_GENRE
          FOREIGN KEY (GENR_ID)
               REFERENCES GENRE (GENR_ID))   ;
-----

ALTER TABLE LIVRER ADD (
     CONSTRAINT FK_LIVRER_ARTICLE
          FOREIGN KEY (ART_NUM)
               REFERENCES ARTICLE (ART_NUM))   ;

ALTER TABLE CLASSIFIER ADD (
     CONSTRAINT FK_CLASSIFIER_ARTICLE
          FOREIGN KEY (ART_NUM)
               REFERENCES ARTICLE (ART_NUM))   ;

ALTER TABLE CLASSIFIER ADD (
     CONSTRAINT FK_CLASSIFIER_CATEGORIE
          FOREIGN KEY (CAT_ID)
               REFERENCES CATEGORIE (CAT_ID))   ;

ALTER TABLE ECRIRE ADD (
     CONSTRAINT FK_ECRIRE_ARTICLE
          FOREIGN KEY (ART_NUM)
               REFERENCES ARTICLE (ART_NUM))   ;

ALTER TABLE ECRIRE ADD (
     CONSTRAINT FK_ECRIRE_AUTEUR
          FOREIGN KEY (AUT_ID)
               REFERENCES AUTEUR (AUT_ID))   ;

ALTER TABLE CONTENIR ADD (
     CONSTRAINT FK_CONTENIR_ARTICLE
          FOREIGN KEY (ART_NUM)
               REFERENCES ARTICLE (ART_NUM))   ;

-----               

ALTER TABLE FOURNIR ADD (
     CONSTRAINT FK_FOURNIR_FOURNISSEUR
          FOREIGN KEY (FRN_ID)
               REFERENCES FOURNISSEUR (FRN_ID))   ;

ALTER TABLE FOURNIR ADD (
     CONSTRAINT FK_FOURNIR_ARTICLE
          FOREIGN KEY (ART_NUM)
               REFERENCES ARTICLE (ART_NUM))   ;