 
  CREATE UNIQUE INDEX "G02_BOOK"."PK_LIVRAISON" ON "G02_BOOK"."LIVRAISON" ("LIVR_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_LIVRER
--------------------------------------------------------

  CREATE UNIQUE INDEX "G02_BOOK"."PK_LIVRER" ON "G02_BOOK"."LIVRER" ("LIVR_NUM", "ART_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_PAIEMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "G02_BOOK"."PK_PAIEMENT" ON "G02_BOOK"."PAIEMENT" ("PAY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index PK_THEMATISER
--------------------------------------------------------

  CREATE UNIQUE INDEX "G02_BOOK"."PK_THEMATISER" ON "G02_BOOK"."THEMATISER" ("ART_NUM", "GENR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_IX_LIVRAISON_DATE
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_IX_LIVRAISON_DATE" ON "G02_BOOK"."LIVRAISON" ("LIVR_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_ECRIRE_AUTEUR
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_ECRIRE_AUTEUR" ON "G02_BOOK"."ECRIRE" ("AUT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_LIVRAISON_COMMANDE
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_LIVRAISON_COMMANDE" ON "G02_BOOK"."LIVRAISON" ("CMD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_IX_CLIENT_NOM
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_IX_CLIENT_NOM" ON "G02_BOOK"."CLIENT" ("CLI_NOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_IX_ARTICLE_NOM1
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_IX_ARTICLE_NOM1" ON "G02_BOOK"."ARTICLE" ("ART_NOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_CLASSIFIER_ARTICLE
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_CLASSIFIER_ARTICLE" ON "G02_BOOK"."CLASSIFIER" ("ART_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_FOURNIR_FOURNISSEUR
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_FOURNIR_FOURNISSEUR" ON "G02_BOOK"."FOURNIR" ("FRN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_IX_AUTEUR_NOM
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_IX_AUTEUR_NOM" ON "G02_BOOK"."AUTEUR" ("AUT_NOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_LIVRER_ARTICLE
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_LIVRER_ARTICLE" ON "G02_BOOK"."LIVRER" ("ART_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_THEMATISER_GENRE
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_THEMATISER_GENRE" ON "G02_BOOK"."THEMATISER" ("GENR_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_IX_PAIMENT_DATE
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_IX_PAIMENT_DATE" ON "G02_BOOK"."PAIEMENT" ("PAY_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_IX_COMMANDE_DATE
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_IX_COMMANDE_DATE" ON "G02_BOOK"."COMMANDE" ("CMD_DATE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_CONTENIR_ARTICLE
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_CONTENIR_ARTICLE" ON "G02_BOOK"."CONTENIR" ("ART_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_CONTENIR_COMMANDE
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_CONTENIR_COMMANDE" ON "G02_BOOK"."CONTENIR" ("CMD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_THEMATISER_ARTICLE
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_THEMATISER_ARTICLE" ON "G02_BOOK"."THEMATISER" ("ART_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_CLASSIFIER_CATEGORIE
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_CLASSIFIER_CATEGORIE" ON "G02_BOOK"."CLASSIFIER" ("CAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_IX_ARTICLE_NOM
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_IX_ARTICLE_NOM" ON "G02_BOOK"."FOURNISSEUR" ("FRN_NOM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_IX_ARTICLE_ISBN
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_IX_ARTICLE_ISBN" ON "G02_BOOK"."ARTICLE" ("ART_ISBN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_ECRIRE_ARTICLE
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_ECRIRE_ARTICLE" ON "G02_BOOK"."ECRIRE" ("ART_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_ARTICLE_EDITEUR
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_ARTICLE_EDITEUR" ON "G02_BOOK"."ARTICLE" ("EDIT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_LIVRER_LIVRAISON
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_LIVRER_LIVRAISON" ON "G02_BOOK"."LIVRER" ("LIVR_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_FOURNIR_ARTICLE
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_FOURNIR_ARTICLE" ON "G02_BOOK"."FOURNIR" ("ART_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_PAIEMENT_COMMANDE
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_PAIEMENT_COMMANDE" ON "G02_BOOK"."PAIEMENT" ("CMD_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "BD50_DATA" ;
--------------------------------------------------------
--  DDL for Index I_FK_COMMANDE_CLIENT
--------------------------------------------------------

  CREATE INDEX "G02_BOOK"."I_FK_COMMANDE_CLIENT" ON "G02_BOOK"."COMMANDE" ("CLI_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "BD50_DATA" ;