

DROP INDEX "I_IX_ARTICLE_ISBN";
DROP INDEX "I_IX_ARTICLE_NOM";
DROP INDEX "I_IX_ARTICLE_NOM1";
DROP INDEX "I_IX_AUTEUR_NOM";
DROP INDEX "I_IX_CLIENT_NOM";
DROP INDEX "I_IX_COMMANDE_DATE";
DROP INDEX "I_IX_LIVRAISON_DATE";
DROP INDEX "I_IX_PAIMENT_DATE";
